---
- name: clone cluegetter
  git: dest=/opt/cluegetter clone=yes repo=https://github.com/Freeaqingme/ClueGetter force=yes
  when: cluegetter.build
  register: cg_git
  notify:
    - build cluegetter
- block:
  - name: install cluegetter dependecies
    apt: name={{ item }} state=present
    with_items:
      - go
      - libspf2-dev
      - libmilter-dev
  - name: build deb
    shell: executable=/bin/bash cd /opt/cluegetter && PATH="/opt/go/bin:$PATH" make deb
  - name: install cluegetter
    apt: deb=/opt/cluegetter/cluegetter.deb
    notify:
      - restart cluegetter
  when: cg_git.changed
- name: update cluegetter configs
  template: src=templates/cluegetter/cluegetter.conf.j2 dest=/etc/cluegetter/cluegetter.conf
  notify:
    - reload cluegetter
