---
- name: install lets encrypt dependecies
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - git
    - python-pip
    - python-virtualenv
    - dialog
    - libaugeas0
    - ca-certificates
- name: install python lets encrypt dependecies
  pip: name=cryptography
- name: deploying certbot
  git: dest=/opt/certbot clone=yes repo=https://github.com/certbot/certbot force=yes